server:
  port: 8081

spring:
  application:
    name: rabbit-receiver
  rabbitmq:
    host: 192.168.132.129
    port: 5672
    username: xxx
    password: xxx
    listener:
      simple:
        retry:
          max-attempts: 5 #最大重试次数
          initial-interval: 5000ms #重试间隔时间
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
        default-requeue-rejected: true #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
